//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace AAMRO_CRM.Modules {
    
    
    public partial class FreightForwarding {
        
        /// <summary>
        /// Master property.
        /// </summary>
        /// <remarks>
        /// Auto-generated property.
        /// </remarks>
        public new AAMRO_CRM.Aamro Master {
            get {
                return ((AAMRO_CRM.Aamro)(base.Master));
            }
        }
    }
}
